// Web projects data
import pixelPrompta from '$lib/images/pixel-prompt.avif';
import twaa from '$lib/images/twa.avif';
import credentialsa from '$lib/images/credentials.avif';
import connectora from '$lib/images/connector.avif';
import plotPalettea from '$lib/images/plotpalette.avif';
import whoamia from '$lib/images/name-check.avif';
import nbaa from '$lib/images/nba.avif';
import instanta from '$lib/images/instant.avif';

import one from '$lib/images/slices/1.jpg';
import two from '$lib/images/slices/2.jpg';
import three from '$lib/images/slices/3.jpg';
import four from '$lib/images/slices/4.jpg';
import five from '$lib/images/slices/5.jpg';
import six from '$lib/images/slices/6.jpg';
import seven from '$lib/images/slices/7.jpg';
import eight from '$lib/images/slices/8.jpg';

export interface WebProject {
  id: string;
  title: string;
  link?: string;
  description?: string;
  initialImg: string;
  activeImg: string;
}

export const webProjects: WebProject[] = [
  {
    id: 'pixel-prompt',
    title: 'Pixel Prompt',
    link: 'https://production.d2iujulgl0aoba.amplifyapp.com/',
    description: 'A web application, built with React Native, AWS Amplify and AWS Lambda, that empowers users to generate and explore AI-driven artwork through diffusion models. Central to its functionality is an IP Adapter plugin that interfaces with a SDXL model, enabling users to apply modifications to their images style and layouts. The application supports seamless switching between popular diffusion models, giving users the flexibility to experiment. A built-in prompt generator further enhances the experience, helping users understand how different prompts influence AI outputs.',
    initialImg: one,
    activeImg: pixelPrompta
  },
  {
    id: 'twa',
    title: 'The Writers Almanac',
    link: 'https://d6d8ny9p8jhyg.cloudfront.net/',
    description: 'This React-powered web application is a digital poetry archive inspired by The Writer\'s Almanac that is hosted on Minnesota Public Radio. Featuring a custom tsparticles background that evokes the texture of ink on paper, the app integrates OpenAI\'s Whisper for audio transcription and will soon include poet biographies and poem analysis generated by Meta Llama 3.1. The platform will provide contextual depth through a fine-tuned LLM with RAG implementation, and will also offer curated links to other prominent websites featuring the poets\' works, creating a comprehensive digital poetry resource.',
    initialImg: two,
    activeImg: twaa
  },
  {
    id: 'credentials',
    title: 'Credentials Canvas',
    link: 'https://production.dld9ll6ojjns2.amplifyapp.com/',
    description: 'A dynamic 3D portfolio experience crafted using Three.js and React Fiber, this immersive digital environment transforms into an interactive journey. Built with a Blender-generated .gltf file optimized through Draco compression, the portfolio offers a richly detailed landscape where phones, lights, arcade controls, signage, and antennas are fully interactive/clickable. Designed for modern hardware, this portfolio explores how technical work can be presented and browsed.',
    initialImg: three,
    activeImg: credentialsa
  },
  {
    id: 'connector',
    title: 'Google Forms to Snowflake Connector',
    link: 'https://docs.google.com/forms/d/e/1FAIpQLSce94QihTjunjBvYzFdalz0mYGhVS6Ngy17uRrXkqLI_Da7nA/viewform?pli=1',
    description: 'This Node.js-based service provides a seamless connection between Google Forms (via App Scripts) and Snowflake, offering a lightweight and cost-effective alternative to traditional data pipelines like Rivery and Fivetran. Built with a serverless architecture, the custom connector enables form submissions to populate in Snowflake within approximately 1-2 minutes. The service leverages existing tools to simplify data integration, eliminating the complexity and expense of larger pipeline solutions. The Data will populate <a href="https://hatmanstack-streamlit-display-app-kicv24.streamlit.app/"><b>HERE</b></a>',
    initialImg: four,
    activeImg: connectora
  },
  {
    id: 'plot-palette',
    title: 'Plot Palette',
    link: 'https://github.com/HatmanStack/plot-palette',
    description: 'Created to finetune LLMs, Plot Pallete is a Dataset to generate Ideas for creative writing. It comes in 10K and 100K sizes and is easily deployed using the DataSet library from HuggingFace. The Dataset includes five tasks that the data was generated from: Creative Writing, Open Question, Poem, Question Answer, and BrainStorm.',
    initialImg: five,
    activeImg: plotPalettea
  },
  {
    id: 'name-check',
    title: 'Name Check',
    link: 'https://github.com/HatmanStack/snow-flask-whoami',
    description: 'This application demonstrates serverless architectures across the three major cloud providers: <a href="https://snow-flask-whoami-gpc-k6cy6vf2la-uc.a.run.app/" target="_blank" rel="noopener noreferrer"><b>Google Cloud Run</b></a>, <a  href="https://l1roun0jr9.execute-api.us-west-1.amazonaws.com/dev" target="_blank" rel="noopener noreferrer"><b>AWS Lambda</b></a>, and <a  href="https://snow-flask-whoami-az.azurewebsites.net/Home" target="_blank" rel="noopener noreferrer"><b>Azure Functions</b></a>. Each backend operates on the same Snowflake database, showcasing their ability to handle a unified workload. Built with Flask for backend logic and Vega-Lite for generating interactive charts, the app highlights the effects of cold starts across providers. Users can interact with the app to initiate workloads, observe how changes propagate between providers, and compare startup performance.',
    initialImg: six,
    activeImg: whoamia
  },
  {
    id: 'nba',
    title: 'NBA Stats',
    link: 'https://hatmanstack-streamlit-nba-app-dz3nxx.streamlit.app/',
    description: 'This interactive application, built with Streamlit.io, turns NBA analytics into an engaging prediction challenge. At its core is a custom Keras machine learning model trained on comprehensive 2018 season data, designed to predict game outcomes based on players\' seasonal performance averages. Users can craft dream teams using players from NBA history and pit them against AI-generated squads tailored to four distinct difficulty levels. For transparency and learning, both the training dataset and model script are accessible through the project\'s <a href="https://github.com/HatmanStack/streamlit-nba" target="_blank" rel="noopener noreferrer"><b>GitHub repository</b></a>.',
    initialImg: seven,
    activeImg: nbaa
  },
  {
    id: 'instant',
    title: 'InstantStyle FLUX & SDXL',
    link: 'https://hatman-instantstyle-flux-sdxl.hf.space/',
    description: 'This is a Gradio application designed for advanced image generation, leveraging the IP Adapter with InstantStyle to transfer styles and layouts dynamically. Running on a Hugging Face space with ZeroGPU architecture, the app allows users to precisely control style transfer by selectively activating or deactivating different layers of two different diffusion models. Users can choose to apply style, layout, both, or neither to the generated image, providing a flexible approach to AI-powered image transformation.',
    initialImg: eight,
    activeImg: instanta
  }
];

export const webContentMap = webProjects.reduce((acc, project) => {
  acc[project.title] = project;
  return acc;
}, { 'Splash': { title: 'Web Stuff' } } as Record<string, any>);